#!/bin/bash
# Example script for scoring sequences for all ensembles
# generated by examples/scripts/generate_ensembles.sh.

source env_setup.sh
python3 caliby/eval/sampling/score_ensemble.py \
    ckpt_name_or_path=caliby \
    input_cfg.conformer_dir=examples/outputs/generate_ensembles/cc95-epoch3490-sampling_partial_diffusion-ss1.0-schurn0-ccstart0.0-dx0.0-dy0.0-dz0.0-rewind150 \
    out_dir=examples/outputs/score_ensemble
