#!/bin/bash
# Example script for designing sequences for all ensembles
# generated by examples/scripts/generate_ensembles.sh.

CONFORMER_DIR=examples/outputs/generate_ensembles/cc95-epoch3490-sampling_partial_diffusion-ss1.0-schurn0-ccstart0.0-dx0.0-dy0.0-dz0.0-rewind150

source env_setup.sh
python3 caliby/eval/sampling/seq_des_ensemble.py \
    ckpt_name_or_path=caliby \
    input_cfg.conformer_dir=${CONFORMER_DIR} \
    sampling_cfg_overrides.num_seqs_per_pdb=4 \
    out_dir=examples/outputs/seq_des_ensemble
